{
  "Header": {
    "Original": "CVE-2018-8768 (In Jupyter Notebook before 5.4.1, a maliciously forged notebook file c ...)",
    "ID": "CVE-2018-8768",
    "Description": "(In Jupyter Notebook before 5.4.1, a maliciously forged notebook file c ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2432-1}",
      "Type": "xref",
      "Bugs": [
        "DLA-2432-1"
      ]
    },
    {
      "Original": "- jupyter-notebook 5.4.1-1 (bug #893436)",
      "Type": "package",
      "Package": "jupyter-notebook",
      "Kind": "fixed",
      "Version": "5.4.1-1",
      "BugNo": 893436
    },
    {
      "Original": "- ipython 5.1.0-2",
      "Type": "package",
      "Package": "ipython",
      "Kind": "fixed",
      "Version": "5.1.0-2"
    },
    {
      "Original": "[jessie] - ipython \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "jessie",
      "Package": "ipython",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[wheezy] - ipython \u003cignored\u003e (Too invasive to fix)",
      "Type": "package",
      "Release": "wheezy",
      "Package": "ipython",
      "Kind": "ignored",
      "Description": "Too invasive to fix"
    },
    {
      "Original": "NOTE: After the reupload of ipython to Debian as 4.1.2-1 via experimental",
      "Type": "NOTE",
      "Description": "After the reupload of ipython to Debian as 4.1.2-1 via experimental"
    },
    {
      "Original": "NOTE: src:ipython does not provide anymore the Notebook",
      "Type": "NOTE",
      "Description": "src:ipython does not provide anymore the Notebook"
    },
    {
      "Original": "NOTE: https://www.openwall.com/lists/oss-security/2018/03/15/2",
      "Type": "NOTE",
      "Description": "https://www.openwall.com/lists/oss-security/2018/03/15/2"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/jupyter/notebook/commit/4e79ebb49acac722b37b03f1fe811e67590d3831",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/jupyter/notebook/commit/4e79ebb49acac722b37b03f1fe811e67590d3831"
    },
    {
      "Original": "NOTE: Ipython in Wheezy lacks sanitization of untrusted HTML completely",
      "Type": "NOTE",
      "Description": "Ipython in Wheezy lacks sanitization of untrusted HTML completely"
    },
    {
      "Original": "NOTE: which means in theory this CVE does not apply. However due to the absence of",
      "Type": "NOTE",
      "Description": "which means in theory this CVE does not apply. However due to the absence of"
    },
    {
      "Original": "NOTE: sanitization it is recommended not to use Ipython's notebook with untrusted",
      "Type": "NOTE",
      "Description": "sanitization it is recommended not to use Ipython's notebook with untrusted"
    },
    {
      "Original": "NOTE: content. This issue is no-dsa because it cannot be determined if Ipython",
      "Type": "NOTE",
      "Description": "content. This issue is no-dsa because it cannot be determined if Ipython"
    },
    {
      "Original": "NOTE: in Wheezy is still affected, a fix appears to be to intrusive though. We recommend to",
      "Type": "NOTE",
      "Description": "in Wheezy is still affected, a fix appears to be to intrusive though. We recommend to"
    },
    {
      "Original": "NOTE: upgrade to a newer version instead.",
      "Type": "NOTE",
      "Description": "upgrade to a newer version instead."
    }
  ]
}